Converting to ts
jpitucha/houston pull request #13
Opened 2020-12-07 00:21 UTC by jpitucha

resolves #3

2020-12-07 00:38 UTC, Jordan141 requested changes
Minimal changes requested. Fix them and I'll approve.

2020-12-07 00:38 UTC, Jordan141 commented on src/api/n2yo/index.ts
> +        console.log(endPoint)
Delete the console.log

2020-12-07 00:42 UTC, Jordan141 approved these changes

2020-12-07 14:40 UTC, michaelKurowski requested changes

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +    // "noUnusedLocals": true,                /* Report errors on unused locals. */
uncomment

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
uncomment

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
Uncomment

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
Uncomment

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
Uncomment

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
>    },
Add "start" script inside "scripts"

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
>    },
It's a standard, you should be able to run any node application by simply typing `npm start`.

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
>    },
start script is a script that runs once you do it

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
> +    "@types/node-fetch": "^2.5.7",
Add eslint
`npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin patch-package`

Create `.eslintignore`, paste this:
```
build
node_modules
```

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
>    },
Add also "lint" script
`"lint": "npx eslint ./src --ext .ts"`

2020-12-07 14:40 UTC, michaelKurowski commented on tsconfig.json
> +{
Create file `.vscode/settings.json` and paste this inside:
```
{
  "typescript.tsdk": "./node_modules/typescript/lib"
}
```
It will make VSC use TS version installed inside the node_modules for errors highlighting

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
>    },
Script should look like this:

`"start": "npm run lint && npx tsc"`

Note that to work it also requires the above script `lint` to be added.

2020-12-07 14:40 UTC, michaelKurowski commented on package.json
> +    "@types/node-fetch": "^2.5.7",
`@types/node-fetch` has some types messed up.
1. edit `node_modules/@types/node-fetch/index.d.ts`

2. replace
```
    constructor(body?: any, opts?: { size?: number; timeout?: number });
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    body: NodeJS.ReadableStream;
    bodyUsed: boolean;
    buffer(): Promise<Buffer>;
    json(): Promise<any>;
    size: number;
    text(): Promise<string>;
    textConverted(): Promise<string>;
    timeout: number;
```

with
```
    constructor(body?: unknown, opts?: { size?: number; timeout?: number });
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    body: NodeJS.ReadableStream;
    bodyUsed: boolean;
    buffer(): Promise<Buffer>;
    json(): Promise<unknown>;
    size: number;
    text(): Promise<string>;
    textConverted(): Promise<string>;
    timeout: number;
```
3. Run `npx patch-package`
4. add below script to scripts
`"postinstall": "patch-package"`

2020-12-07 14:40 UTC, michaelKurowski commented on src/api/n2yo/index.ts
> +            .catch(err => console.warn(err))
You should send response upon catch, even if it's an error response. Otherwise HTTP request will stuck pending on browser side.

2020-12-07 14:43 UTC, michaelKurowski commented on src/routes/local.ts
> +        .then(data => res.json(data))
`getTwoLineElements` already sends the response. It will be probably better to remove it from inside `getTwoLineElements`

2020-12-07 23:41 UTC, michaelKurowski requested changes

2020-12-07 23:41 UTC, michaelKurowski commented on tsconfig.json
> +    // "noUncheckedIndexedAccess": true,      /* Include 'undefined' in index signature results */
I forgot about this one, please uncomment as well

2020-12-07 23:41 UTC, michaelKurowski commented on package.json
>  }
I've apperently forgot about creating file `.eslintrc`
```
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended"
  ],
  "rules": {
    "@typescript-eslint/no-explicit-any": 2
  }
}
```

Also  looks like you didn't install the packages I asked for.
`npm install --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin patch-package`

they're not listen in package.json here

2020-12-07 23:41 UTC, michaelKurowski commented on package.json
>  }
After you'll introduce these things, linter will find issues with your code
`npm run lint`


```
/home/mkurowski/OSS/houston/src/api/n2yo/index.ts
  7:5   warning  Missing return type on function                                               @typescript-eslint/explicit-module-boundary-types
  8:15  error    Type string trivially inferred from a string literal, remove type annotation  @typescript-eslint/no-inferrable-types

/home/mkurowski/OSS/houston/src/index.ts
  6:5  error  'app' is never reassigned. Use 'const' instead  prefer-const
```
Get rid of them

2020-12-07 23:43 UTC, michaelKurowski commented on tsconfig.json
> +    // "noUncheckedIndexedAccess": true,      /* Include 'undefined' in index signature results */
```
src/routes/local.ts:7:29 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

7     n2yo.getTwoLineElements(req.params.id)
```
Once introducing this change your code throws this.

You need to make type guard for `req.params.id` to make it pass

2020-12-07 23:43 UTC, michaelKurowski commented
After introducing these changes build your app with `npm start`, it has to run without errors

2020-12-08 10:20 UTC, michaelKurowski commented
Also `npm start` that I told u to write will only build your project, you can modify it to serve files after compiling them.

2020-12-08 21:47 UTC, michaelKurowski approved these changes

2020-12-08 22:19 UTC, Jordan141 approved these changes

2020-12-08 22:21 UTC, merged