Base guest functionalities
jpitucha/houston pull request #20
Opened 2021-01-10 01:44 UTC by jpitucha

resolves #9

2021-01-10 02:10 UTC, bilgorajskim requested changes

2021-01-10 02:10 UTC, bilgorajskim commented on src/routes/local.ts
> +router.get('/satellite', (req, res) => {
This is a GET route, but your handler reads from `req.body`. GET requests have no body [0]. You probably meant to read query parameters. You can use `req.query` for that.

[0] GET requests can technically be sent with body, but browsers typically don't allow it.

2021-01-10 02:31 UTC, Jordan141 requested changes

2021-01-10 02:31 UTC, Jordan141 commented on src/routes/local.ts
> +            .then((doc) => {
Give doc a more descriptive name, maybe satellite or satelliteDoc in this instance, do it for all instances of doc.

2021-01-10 02:31 UTC, Jordan141 commented on src/utils/satelliteUtils.ts
> +        return Satellite.countDocuments().exec()
Remember that in large databases, esimatedDocumentCount is a significantly more performant option as it doesn't try to count the entire document list.  However, in this case countDocuments is fine, just keep it in mind.

2021-01-10 02:31 UTC, Jordan141 commented on src/utils/satelliteUtils.ts
> +            await Satellite.create(newSatelite)
as much as I prefer async/await, this project is about you learning promises, stick with them.

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +            .catch(() => { return res.sendStatus(400) })
It's a stylistic thing and depends on the taste,
but you can write this thing as `.catch(() => res.sendStatus(400))`

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +            .catch(() => { return res.sendStatus(400) })
In general, if you immediately want to return value in arrow (aka lambda) functions, you can omit curly bracers and the `return` keyword.
So `() => { return x }` becomes `() => x`. If there's only one arguments, you can also ommit parenthesis that wraps argument section so `(myArg) => {...}` becomes `myArg => {...}`.
Combining these two principles can create some neat and clean code i.e.
`(a) => {return a * 2}` can become `a => a * 2`

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +    if (req.body.id === undefined && req.body.name === undefined) return res.sendStatus(400)
If you'll receive `NaN`, `null`, `0` or `''` as `.name` or `.id`, you will end up with pending http request, never responding to it.

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +const propsToPick = ['_id', 'officialName', 'perigee', 'apogee', 'operator', 'operatorCountry', 'purpose']
Give it a more descriptive name.

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +const propsToPick = ['_id', 'officialName', 'perigee', 'apogee', 'operator', 'operatorCountry', 'purpose']
Also it's a primitive constant it should be `WRITTEN_IN_THIS_MANNER`.

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +    if (req.body.id === undefined && req.body.name === undefined) return res.sendStatus(400)
Also, you use lodash, so you can use `_.isUndefined(x)`. It won't fix the issues i've pointed out, it's more like a tip for the future.

2021-01-10 18:20 UTC, michaelKurowski commented on src/utils/satelliteUtils.ts
> +            throw 'error occured while putting new satellite'
Why do you do this, do you want to hide the original error? If you'll get an error from `createSatelite`, you'll still get unhandled promise rejection.

2021-01-10 18:20 UTC, michaelKurowski commented on src/utils/satelliteUtils.ts
> +    static getSatelliteByName(name: string): Promise<SatelliteInterface | null> {
Is it the `SatelliteInterface`? Isn't that a mongoose document?

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +    if (req.params.name === undefined) return res.sendStatus(400)
If you'll get  `NaN`, `null`, `0` or `''` as `params.name`, you'll end up with pending http request.

2021-01-10 18:20 UTC, michaelKurowski commented on src/routes/local.ts
> +    if (req.body.name) {
If you'll get  `NaN`, `null`, `0` or `''` as `req.body.name`, you'll end up with pending http request.

2021-01-10 18:21 UTC, michaelKurowski commented
Can you query satellites by codes in your PR, or only by names?

2021-01-10 22:07 UTC, jpitucha commented
I can query them both by ID and the name @michaelKurowski

2021-01-10 22:11 UTC, Jordan141 approved these changes

2021-01-10 22:41 UTC, bilgorajskim approved these changes

2021-01-11 01:31 UTC, michaelKurowski approved these changes

2021-01-11 06:35 UTC, merged